import { useState } from 'react';
import { api } from '../services/api';

export default function ActiveDelivery() {
  const [bookingId, setBookingId] = useState('');
  const [isSimulating, setIsSimulating] = useState(false);
  const [stats, setStats] = useState(0);

  const simulateDriving = () => {
    setIsSimulating(true);
    let lat = 19.0760; // Mumbai base
    let lng = 72.8777;

    setInterval(async () => {
      lat += (Math.random() * 0.0005) + 0.0001; // organic movement simulation
      lng += (Math.random() * 0.0005) + 0.0001; 
      
      setStats(prev => prev + 1);

      await api.post('/location', {
        bookingId,
        captainId: 'captain-uuid-999',
        lat,
        lng
      }).catch(console.error);
    }, 1000); // 1-second burst SSE
  };

  return (
    <div style={{ padding: '2rem' }}>
      <h2 style={{color: '#ff6a00', marginBottom: '0.5rem'}}>Active Delivery Dispatch</h2>
      <p style={{color: 'var(--text-light)'}}>Continuously stream highly accurate GPS data to Customer.</p>
      
      <div className="glass-card" style={{ maxWidth: '400px', marginTop: '1.5rem', borderLeft: '4px solid #ff6a00' }}>
         <h3 style={{marginTop: 0, color: '#374151'}}>Dispatch Connection Link</h3>
         <p style={{fontSize: '0.9rem', color: '#6B7280'}}>Enter the unique Booking ID generated by the Customer to transmit live coordinates via SSE.</p>
         
         <input 
            type="text" 
            placeholder="INV-XXXX"
            value={bookingId}
            onChange={(e) => setBookingId(e.target.value)}
            style={{ width: '100%', boxSizing: 'border-box', padding: '14px', marginBottom: '1.5rem', borderRadius: '8px', border: '1px solid #D1D5DB', fontSize: '1.1rem' }}
         />
         
         <button 
           className="btn-primary" 
           onClick={simulateDriving} 
           disabled={isSimulating || !bookingId} 
           style={{ width: '100%', padding: '15px', fontSize: '1.05rem', background: 'linear-gradient(135deg, #ff8c00, #ff6a00)', border: 'none', borderRadius: '8px' }}>
            {isSimulating ? `Transmitting Active Data... (${stats} pings)` : 'Start Tracking Transmission'}
         </button>
      </div>
    </div>
  );
}
